name: CI and Continuous Delivery Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image (CI)
        run: |
          docker build -t networksecurity2-ml-2026 .

  cd:
    name: Continuous Delivery (ECR)
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password \
          | docker login --username AWS --password-stdin \
          260735202232.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push Docker Image to ECR (CD)
        run: |
          docker tag networksecurity2-ml-2026:latest \
          260735202232.dkr.ecr.ap-south-1.amazonaws.com/networksecurity2-ml-2026:latest
          docker push \
          260735202232.dkr.ecr.ap-south-1.amazonaws.com/networksecurity2-ml-2026:latest
